openapi: 3.0.1
info:
  title: transport
  description: API Definition of transport
  version: 1.0.0
servers:
- url: http://localhost:8290/order
paths:
  /kafka:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /simple:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
